### ISSUE TITLE
Issue during install

### ISSUE THREAD

**Issue by kchetan92** [Kikobeats/free-email-domains#2]
xxx/xxx/node_modules/free-email-domains/scripts/postinstall:12

;(async () => {
        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

Got this issue while using NPM to install

**Comment by Kikobeats** [comment]
Hmm what node version are you running?

**Comment by Kikobeats** [comment]
I confirm this happens when you are running a old node version (<8)

Sorry, just upgrade it 🙂
